# Generated by Django 4.1.12 on 2023-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
